spring:
  profiles:
    active: local
#aws s3 local Test
cloud:
  aws:
    stack:
      auto : false
    credentials:
      instanceProfile : true #aws의 instanceProfile을 사용하겠다.
    s3 :
      bucket : netflixsharebucket
    region :
      static : ap-northeast-2

---

spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/newtestdb2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    dbcp2:
      time-between-eviction-runs-millis: 60000 #이건 뺄 수도 있을듯
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

---

spring:
  profiles: operation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newtestdb2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    dbcp2:
      time-between-eviction-runs-millis: 60000 #이건 뺄 수도 있을듯
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000

server:
  ssl:
    key-store: keystore.p12
    key-store-password: rootpassword
    key-store-type: PKCS12
    key-alias: tomcat

