spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/newtestdb2?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: rootpassword
    dbcp2:
      time-between-eviction-runs-millis: 60000 #이건 뺄 수도 있을듯

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

    show-sql: true

app:
  jwtSecret: JWTSuperSecretKey
  jwtExpirationInMs: 604800000